# Logvault Configuration

# Syslog server settings
syslog:
  host: "0.0.0.0"
  port: 514
  protocol: "udp"

# Redis settings
redis:
  address: "localhost:6379"
  password: ""
  db: 0

# Web UI settings
web:
  port: 8080
  secret: "your_secret_password" # Add your secret here

# API settings
api:
  bearer_token: "your_bearer_token" # Choose a strong, unique token
